In [1]:
import datetime

import numpy as np
import pandas as pd
import pandas_datareader as pdr  # IF NECESSARY, from terminal: pip install pandas_datareader
from numpy.random import default_rng

pd.set_option("display.max_rows", 10)  # display option for pandas
# more here: https://pandas.pydata.org/pandas-docs/stable/user_guide/options.html

## A quick hit of Numpy

In [3]:
# create a random vector 
# every run of this --> diff #s
# see 3.2.2.2 in the textbook for why, 
# and how to prevent

rg = default_rng()
myray = rg.standard_normal(5)
print("myray:", myray)

myray: [-0.03487973  1.03569813  0.91620124 -0.74851511 -1.12232277]

In [4]:
# q1 - indexing, pick the odd elements
myray[::2]

array([-0.03487973,  0.91620124, -1.12232277])

Booleans arrays: Asking a logic test on an array, returns the array, where each element has been tested against that logic and converted to the boolean answer.

In [6]:
# q2 - (a) boolean array + (b) "masking"

# myray[[1,3,4]] # m,agic nums suck! don't work when the random arRAY IS BUILT AGAIN

# (a)
myray > 0 # this tests every element in the array against the logic

# (b)

array([False,  True,  True, False, False])

What you just learned about masking and filtering can be done with dataframes!

## The main event - Pandas

Vocab
- series
- index 
- dataframe
- columns and names
- rows and index 
- multiindex

In [9]:
start = datetime.datetime(2017, 1, 1) # you can specify start and end dates this way
end = datetime.datetime(2021, 1, 27)
macro_df = pdr.data.DataReader(['GDP','CPIAUCSL','UNRATE'], 'fred', start, end)

In [10]:
# preview the dataframe
macro_df                 # just print some default top and bottom
macro_df.head(20)        # Look at the top tail
macro_df.tail(10)        # Look at the bottom tail

macro_df[30:40]          # You can slice it like a list

macro_df.sample(20)
macro_df.sample(frac = .3)

# If you installed variable inspector in the setup 
# right click > open your inspector > pick the var, look

                  GDP  CPIAUCSL  UNRATE
DATE
2020-04-01  19935.444   256.126    14.8
2018-03-01        NaN   249.577     4.0
2019-03-01        NaN   254.277     3.8
2020-03-01        NaN   258.150     4.4
2017-01-01  19280.084   243.618     4.7
...               ...       ...     ...
2019-12-01        NaN   258.630     3.6
2020-09-01        NaN   259.951     7.8
2017-08-01        NaN   245.183     4.4
2018-10-01  20917.867   252.772     3.8
2018-11-01        NaN   252.594     3.8

[15 rows x 3 columns]

In [11]:
# shape
macro_df.shape

(49, 3)

In [12]:
# variable types
macro_df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 49 entries, 2017-01-01 to 2021-01-01
Freq: MS
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   GDP       17 non-null     float64
 1   CPIAUCSL  49 non-null     float64
 2   UNRATE    49 non-null     float64
dtypes: float64(3)
memory usage: 1.5 KB

In [13]:
# look at top X rows - head

In [14]:
# look at bottom X rows - tail

In [15]:
# grab one variable
macro_df['GDP'] # bracket, name of variable
macro_df['GDP']+1 # e.g. you can manipulate it

DATE
2017-01-01    19281.084
2017-02-01          NaN
2017-03-01          NaN
2017-04-01    19439.643
2017-05-01          NaN
                ...
2020-09-01          NaN
2020-10-01    22069.767
2020-11-01          NaN
2020-12-01          NaN
2021-01-01    22657.793
Freq: MS, Name: GDP, Length: 49, dtype: float64

In [16]:
# grab two (or more) variables
df = macro_df['GDP'] # give it a list od vars

In [17]:
# see column names
macro_df.columns

Index(['GDP', 'CPIAUCSL', 'UNRATE'], dtype='object')

In [18]:
# change column names
# a few ways to do this
new_names = ['GDP','CPI','UNRATE']
macro_df.columns = new_names
macro_df

                  GDP      CPI  UNRATE
DATE
2017-01-01  19280.084  243.618     4.7
2017-02-01        NaN  244.006     4.6
2017-03-01        NaN  243.892     4.4
2017-04-01  19438.643  244.193     4.4
2017-05-01        NaN  244.004     4.4
...               ...      ...     ...
2020-09-01        NaN  259.951     7.8
2020-10-01  22068.767  260.249     6.9
2020-11-01        NaN  260.895     6.7
2020-12-01        NaN  262.005     6.7
2021-01-01  22656.793  262.518     6.4

[49 rows x 3 columns]

In [19]:
# see index
macro_df.index

DatetimeIndex(['2017-01-01', '2017-02-01', '2017-03-01', '2017-04-01',
               '2017-05-01', '2017-06-01', '2017-07-01', '2017-08-01',
               '2017-09-01', '2017-10-01', '2017-11-01', '2017-12-01',
               '2018-01-01', '2018-02-01', '2018-03-01', '2018-04-01',
               '2018-05-01', '2018-06-01', '2018-07-01', '2018-08-01',
               '2018-09-01', '2018-10-01', '2018-11-01', '2018-12-01',
               '2019-01-01', '2019-02-01', '2019-03-01', '2019-04-01',
               '2019-05-01', '2019-06-01', '2019-07-01', '2019-08-01',
               '2019-09-01', '2019-10-01', '2019-11-01', '2019-12-01',
               '2020-01-01', '2020-02-01', '2020-03-01', '2020-04-01',
               '2020-05-01', '2020-06-01', '2020-07-01', '2020-08-01',
               '2020-09-01', '2020-10-01', '2020-11-01', '2020-12-01',
               '2021-01-01'],
              dtype='datetime64[ns]', name='DATE', freq='MS')

In [20]:
# reset_index() and set_index()
macro_df.reset_index() # turns index into a variable

         DATE        GDP      CPI  UNRATE
0  2017-01-01  19280.084  243.618     4.7
1  2017-02-01        NaN  244.006     4.6
2  2017-03-01        NaN  243.892     4.4
3  2017-04-01  19438.643  244.193     4.4
4  2017-05-01        NaN  244.004     4.4
..        ...        ...      ...     ...
44 2020-09-01        NaN  259.951     7.8
45 2020-10-01  22068.767  260.249     6.9
46 2020-11-01        NaN  260.895     6.7
47 2020-12-01        NaN  262.005     6.7
48 2021-01-01  22656.793  262.518     6.4

[49 rows x 4 columns]

In [21]:
macro_df.reset_index().set_index('DATE')

                  GDP      CPI  UNRATE
DATE
2017-01-01  19280.084  243.618     4.7
2017-02-01        NaN  244.006     4.6
2017-03-01        NaN  243.892     4.4
2017-04-01  19438.643  244.193     4.4
2017-05-01        NaN  244.004     4.4
...               ...      ...     ...
2020-09-01        NaN  259.951     7.8
2020-10-01  22068.767  260.249     6.9
2020-11-01        NaN  260.895     6.7
2020-12-01        NaN  262.005     6.7
2021-01-01  22656.793  262.518     6.4

[49 rows x 3 columns]

In [22]:
macro_df.reset_index()
macro_df # no change

                  GDP      CPI  UNRATE
DATE
2017-01-01  19280.084  243.618     4.7
2017-02-01        NaN  244.006     4.6
2017-03-01        NaN  243.892     4.4
2017-04-01  19438.643  244.193     4.4
2017-05-01        NaN  244.004     4.4
...               ...      ...     ...
2020-09-01        NaN  259.951     7.8
2020-10-01  22068.767  260.249     6.9
2020-11-01        NaN  260.895     6.7
2020-12-01        NaN  262.005     6.7
2021-01-01  22656.793  262.518     6.4

[49 rows x 3 columns]

In [23]:
# grab some rows (by position)
macro_df[20:30]

                  GDP      CPI  UNRATE
DATE
2018-09-01        NaN  252.182     3.7
2018-10-01  20917.867  252.772     3.8
2018-11-01        NaN  252.594     3.8
2018-12-01        NaN  252.767     3.9
2019-01-01  21111.600  252.561     4.0
2019-02-01        NaN  253.319     3.8
2019-03-01        NaN  254.277     3.8
2019-04-01  21397.938  255.233     3.7
2019-05-01        NaN  255.296     3.6
2019-06-01        NaN  255.213     3.6

In [24]:
# grab some rows (by value)...One way to query/filter
mask = macro_df['UNRATE'] > 6
macro_df[mask]

                  GDP      CPI  UNRATE
DATE
2020-04-01  19935.444  256.126    14.8
2020-05-01        NaN  255.848    13.2
2020-06-01        NaN  257.004    11.0
2020-07-01  21684.551  258.408    10.2
2020-08-01        NaN  259.366     8.4
2020-09-01        NaN  259.951     7.8
2020-10-01  22068.767  260.249     6.9
2020-11-01        NaN  260.895     6.7
2020-12-01        NaN  262.005     6.7
2021-01-01  22656.793  262.518     6.4

In [25]:
# create a variable
# (2 ways)
macro_df['HIGH'] = mask # df['NAME'] = elur
macro_df.assign(high2 = macro_df['UNRATE'] > 6)
macro_df

                  GDP      CPI  UNRATE   HIGH
DATE
2017-01-01  19280.084  243.618     4.7  False
2017-02-01        NaN  244.006     4.6  False
2017-03-01        NaN  243.892     4.4  False
2017-04-01  19438.643  244.193     4.4  False
2017-05-01        NaN  244.004     4.4  False
...               ...      ...     ...    ...
2020-09-01        NaN  259.951     7.8   True
2020-10-01  22068.767  260.249     6.9   True
2020-11-01        NaN  260.895     6.7   True
2020-12-01        NaN  262.005     6.7   True
2021-01-01  22656.793  262.518     6.4   True

[49 rows x 4 columns]

In [ ]:
# two ways to make "assign" permamenent
# df = df.assign
macro_df.assign(high2 = macro_df['UNRATE'] > 6)

#2 df.assign(
macro_df.assign(high2 = macro_df['UNRATE'] > 6)

                  GDP      CPI  UNRATE   HIGH  high2
DATE
2017-01-01  19280.084  243.618     4.7  False  False
2017-02-01        NaN  244.006     4.6  False  False
2017-03-01        NaN  243.892     4.4  False  False
2017-04-01  19438.643  244.193     4.4  False  False
2017-05-01        NaN  244.004     4.4  False  False
...               ...      ...     ...    ...    ...
2020-09-01        NaN  259.951     7.8   True   True
2020-10-01  22068.767  260.249     6.9   True   True
2020-11-01        NaN  260.895     6.7   True   True
2020-12-01        NaN  262.005     6.7   True   True
2021-01-01  22656.793  262.518     6.4   True   True

[49 rows x 5 columns]

## EDA

Stop here. Back to the lecture. 

### Part 1

Q0: Do each of the [EDA golden rules for initial data exploration](https://ledatascifi.github.io/ledatascifi-2025/content/03/02e_eda_golden.html) and write down your observations.
- **Important: What is the "key" or "unit level" that observations in this database describes?** 
    - This is defined in 3.2.5 and discussed in [3.2.2.2 via example](https://ledatascifi.github.io/ledatascifi-2025/content/03/02b_pandasVocab.html#the-shape-of-data)
    - The "key" levels in databases we will look at are often increments of time in the data, the type of entity describe (e.g. firm, person, state, country, industry), and combinations of entity and time. 
    - E.g. "firm" level, "firm-year" level

In [ ]:
macro_df['GDP'].mean()

In [ ]:
# i learned that gdp is annualized
# data key is "Date" and units are months
# i suspect but haven't shown that the jan gdp is the Q1, gdp, meaning its spread across those three months
# but the gdp again: annualized (and seasonably adjusted)

Q1: What is the second series above?

CPI index (Not inflation!)

pct change from one row to the next

Q2: What is the frequency of the series?

Q3: What is the average ANNUAL GDP, based on the data?

In [ ]:
macro_df['GDP'].mean()*4

## Part 2

Q4: Download the annual *real* gdp from 1960 to 2018 from FRED and compute the average annual percent change

In [ ]:
import datetime
import pandas_datareader as pdr

# Download and compute annual real GDP

beg = datetime.datetime(1960, 1, 1)
end = datetime.datetime(2018, 1, 1)
realGDP = pdr.data.DataReader('GDPCA', 'fred', beg, end)
realGDP.pct_change().mean()

# Compute the percent change

In [ ]:
realGDP['pct.change'] = realGDP['GDPCA'].pct_change()
realGDP.groupby(['decade']).mean() # for each decade, average all variables

realGDP.groupby(['decade']).mean()['pct.change']

In [ ]:
# When your working of a df and Prof doesn't tell us then don't do it

In [ ]:
# I need to know the year of each row
realGDP['year'] = realGDP.index.year
realGDP['decade'] = 10* (realGDP.index.year // 10)
realGDP

In [ ]:
# With () it is a function without it is a attribute

Q5: Compute the average gdp percent change within *each decade*

In [ ]:

dec_realGDP = realGDP[::40].copy()
dec_realGDP['Percent_Change'] = dec_realGDP['GDPCA'].pct_change().fillna(0)
dec_realGDP['pcg'] = dec_realGDP['Percent_Change'].apply(lambda x: x + 1)

dec_am = sum(dec_realGDP['Percent_Change'])/len(dec_realGDP['GDPCA'] - 1)
print("Arithmetic Mean:", dec_am)

product = 1
for i in ann_realGDP['pcg']:
    product *= i

n = len(dec_realGDP['pcg'])
geom_mean = product ** (1 / n) - 1
print("Geometric Mean:", geom_mean)

## Part 3

First, I'll load January data on unemployment, the Case-Shiller housing index, and median household income in three states (CA/MI/PA).

In [ ]:
# LOAD DATA AND CONVERT TO ANNUAL

start = 1990 # pandas datareader can infer these are years
end = 2018
macro_data = pdr.data.DataReader(['CAUR','MIUR','PAUR', # unemployment 
                                  'LXXRSA','DEXRSA','WDXRSA', # case shiller index in LA, Detroit, DC (no PA  available!)
                                  'MEHOINUSCAA672N','MEHOINUSMIA672N','MEHOINUSPAA672N'], #  
                                 'fred', start, end)
macro_data = macro_data.resample('Y').first() # get's the first observation for each variable in a given year

# CLEAN UP THE FORMATING SOMEWHAT

macro_data.index = macro_data.index.year
print("\n\n DATA BEFORE FORMATTING: \n\n")
print(macro_data[:20]) # see how the data looks now? ugly variable names, but its an annual dataset at least
macro_data.columns=pd.MultiIndex.from_tuples([
    ('Unemployment','CA'),('Unemployment','MI'),('Unemployment','PA'),
    ('HouseIdx','CA'),('HouseIdx','MI'),('HouseIdx','PA'),
    ('MedIncome','CA'),('MedIncome','MI'),('MedIncome','PA')
    ])
print("\n\n DATA AFTER FORMATTING: \n\n")
print(macro_data[:20]) # this is a dataset that is "wide", and now 
                       # the column variable names have 2 levels - var name, 
                       # and unit/state that variable applies to

Q6: for each decade and state, report the average annual CHANGE (level, not percent) in unemployment

In [ ]:
# method 1 - index

macro_data['decade'] = macro_data.index // 10) * 10
macro_data

macro_data.diff() # diff is the subtraction function we need

# this is too many columns

macro_data['Unemployment']
macro_data[

Q7: for each decade and state, report the average annual PERCENT CHANGE in house prices and household income